branches:
  only:
    - master
sudo: required
dist: trusty
language: node_js
env: 
  - NPM_PUBLISH_VERSION=none
before_script:
  - git config --global user.email "build-ci@axa.fr"
  - git config --global user.name "Build-CI"
node_js:
  - "10"
install:
  - npm install
  - npm run bootstrap
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage
  - npm run codacy-coverage
  - npm run lint
deploy:
  on:
    all_branches: true
    condition: $NPM_PUBLISH_VERSION =~ ^major|minor|patch|prerelease$
  provider: script
  script: "git reset --hard && git remote set-url origin https://${GH_TOKEN}@github.com/AxaGuilDEv/react-oidc.git && git checkout ${TRAVIS_BRANCH} && cp .npmrc.template $HOME/.npmrc && npm run publish -- ${NPM_PUBLISH_VERSION} --yes --concurrency 1 --force-publish"
  skip_cleanup: true
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
